#!/bin/bash

clear

BASE_VER="XzK"
VER="-i9b2"
BUILD_VER=$BASE_VER$VER

export LOCALVERSION="~"`echo $BUILD_VER`
export CROSS_COMPILE=/home/nik/android/test/AK-linaro/4.8.2-2013.08.20130820/bin/arm-linux-gnueabihf-
export ARCH=arm
export SUBARCH=arm

DATE_START=$(date +"%s")

KERNEL_DIR=`pwd`
OUTPUT_DIR=/home/nik/android/build
ZIMAGE_DIR=$KERNEL_DIR/arch/arm/boot
RAMDISK_DIR=/home/nik/android/build/boot.img-ramdisk
INITRD_DIR=$RAMDISK_DIR/initrd
CWM_DIR=$RAMDISK_DIR/cwm
CWM_ANY_DIR=$RAMDISK_DIR/cwm_any
MODULES_DIR=$CWM_DIR/system/lib/modules
MODULES_ANY_DIR=$CWM_ANY_DIR/system/lib/modules

echo 
echo "Kernel: "$BUILD_VER
echo
echo "LOCALVERSION="$LOCALVERSION
echo "CROSS_COMPILE="$CROSS_COMPILE
echo "ARCH="$ARCH
echo "SUBARCH="$SUBARCH
echo
echo "KERNEL_DIR="$KERNEL_DIR
echo "RAMDISK_DIR="$RAMDISK_DIR
echo "OUTPUT_DIR="$OUTPUT_DIR
echo

echo 
echo "Making defconfig"
echo

# make
make mod_fusion3_defconfig
make xconfig
cp ./.config arch/arm/configs/mod_fusion3_defconfig
make CONFIG_DEBUG_SECTION_MISMATCH=y -j8 > ~/make.log

# copy output files
rm `echo $MODULES_DIR"/*"`
find $KERNEL_DIR -name '*.ko' -exec cp -v {} $MODULES_DIR \;
cp -vr $ZIMAGE_DIR/zImage $RAMDISK_DIR

# create ramdisk
cd $INITRD_DIR
#find . | cpio -o -H newc | gzip > ../ramdisk.cpio.gz
#find . | cpio -o -H newc | xz --check=crc32 --lzma2=dict=8MiB > ../initrd.img

# create boot.img
cd $RAMDISK_DIR
./mkbootimg --base 0x80200000 --kernel zImage --ramdisk_offset 0x02000000 --cmdline "androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x3F ehci-hcd.park=3 vmalloc=400M androidboot.emmc=true" --ramdisk newramdisk.cpio.gz -o boot.img

# create flashable zip
echo
echo "Create flashable zip"
echo
mv boot.img $CWM_DIR
cd $CWM_DIR
zip -r `echo $BUILD_VER`.zip *
mv  `echo $BUILD_VER`.zip $OUTPUT_DIR

# create flashable zip
echo
echo "Create ANY flashable zip"
echo
cd $RAMDISK_DIR
cp zImage $CWM_ANY_DIR/kernel
cp $MODULES_DIR/* $MODULES_ANY_DIR/
cd $CWM_ANY_DIR
zip -r `echo $BUILD_VER`-ANY.zip *
mv  `echo $BUILD_VER`-ANY.zip $OUTPUT_DIR

# clean 
rm -rf $RAMDISK_DIR/zImage
rm -rf $RAMDISK_DIR/initrd.img
rm -rf $CWM_DIR/boot.img
rm -rf $CWM_ANY_DIR/kernel/zImage

echo
echo "Build completed at "$OUTPUT_DIR"/"$BUILD_VER".zip"

cd $KERNEL_DIR

DATE_END=$(date +"%s")
echo
DIFF=$(($DATE_END - $DATE_START))
echo "Build completed in $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) seconds."
